# GitHub Actions Virtual Environments
# https://github.com/actions/virtual-environments/

name: SwiftPM Integration

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/spm-macos.yml'
      - 'Package*'
      - 'Sources/**/*.*'
      - 'Tests/**/*.*'
  pull_request:
    branches:
      - main

env:
  DEVELOPER_DIR: /Applications/Xcode_14.2.app/Contents/Developer

jobs:
  main:
    name: SwiftPM Build
    runs-on: macos-12
    steps:
      - name: git checkout
        uses: actions/checkout@v3

      - name: xcode version
        run: xcodebuild -version -sdk

      - name: swift build
        run: swift build
